version: "3"
# Containers config
services:
  # Name for the container
  api:
    # specify image to run the container under image
    # image: python
    # or give the path of the docker file under build
    build: .

    # Depends on the postgres container.
    depends_on:
      - postgres

    ports:
      # <port on localhost>:<port on container> requests from this port on local host will be forwarded to that port of container
      - 8000:8000

    # Bind mount the volume.
    volumes:
      # Bind the current directory of hostmachine with /usr/src/app dir of container
      - ./:/usr/src/app:ro

    # overwrite the command in dockerfile for development purpose
    command: uvicorn app.main_orm:app --host 0.0.0.0 --port 8000 --reload

    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=0178902364758699019371134567
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  
  # Name for the second container
  postgres: 
    # Name of the image to be downloaded from docker hub
    image: postgres
    # Env Vars
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi

    # Volumes to persist the data it is a named mount
    volumes:
      - postgres-db:/var/lib/postgresql/data

# Volumes to be used by multiple services
volumes:
  postgres-db:




  
